---
- name: Install tools
  hosts: nodes
  become: true
  tasks:
    - name: Install Git and Python 3
      yum:
        name:
        - git
        - python3
        state: present
        update_cache: yes

- name: Install Poetry
  hosts: nodes
  tasks:
    - name: Install Poetry
      shell:
        cmd: 'curl -sSL https://install.python-poetry.org | python3 -'
        creates: ~/.local/bin/poetry

- name: Create To-Do App Directory and clone from GitHub
  hosts: nodes
  become: true
  tasks:
    - name: Create directory
      file:
        path: /opt/todoapp
        state: directory
        owner: ec2-user
    - name: Clone Remote Git Repository
      git:
        repo: https://github.com/aleyipsoftwire/DevOps-Course-Starter.git
        dest: /opt/todoapp

- name: Install dependencies and set env variables
  hosts: nodes
  vars_files:
    - ./vars/env.yml
  tasks:
    - name: Install dependencies
      command: poetry install
      args:
        chdir: /opt/todoapp
    - name: Set env variables  
      template:
        src: .env.j2
        dest: /opt/todoapp/.env

- name: Copy service file and start service
  hosts: nodes
  become: true
  tasks:
    - name: Copy service file
      copy:
        src: todoapp.service
        dest: /etc/systemd/system/todoapp.service
    - name: Start service
      systemd:
        name: todoapp
        daemon_reload: true
        state: restarted
