name: Continuous Integration

on:
  push:
    paths-ignore:
      - "ansible"
      - "README.md"
  pull_request:
    paths-ignore:
      - "ansible"
      - "README.md"

jobs:
  test:
    name: Build docker image and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --target test --tag todo-app:test .
      - run: docker run --env-file .env.test todo-app:test

  deploy:
    name: Build docker image and deploy to production
    runs-on: ubuntu-latest
    needs: test
    if: github.ref_name == github.event.repository.default_branch
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: aleyipsoftwire
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: aleyipsoftwire/todo-app:prod
      - name: Release to Azure
        env:
          AZURE_WEBHOOK: ${{ secrets.AZURE_WEBHOOK }}
        run: curl -X POST "$AZURE_WEBHOOK"
